sudo: required
language: cpp
dist: trusty
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-dev
install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
       brew install qt
       ;
    fi
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - cmake -DCMAKE_BUILD_TYPE=Release && make -j4
